=== KhaledSARRAJ/XML/hbo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- édité avec XMLSpy v2021 (x64) (http://www.altova.com) par Robert Smith (Robert Corporation) -->
<!-- edited with XMLSpy v2008 rel. 2 sp2 (http://www.altova.com) by SHOCK (SHOCK) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="HBO">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="series"/>
				<xs:element ref="employes"/>
				<xs:element ref="contrats"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="series">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="serie" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="serie">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="titre"/>
				<xs:element ref="synopsis"/>
				<xs:element ref="dateDiffusion"/>
				<xs:element ref="nbSaison"/>
				<xs:element ref="personnages"/>
			</xs:sequence>
			<xs:attribute name="codeSerie" type="xs:ID" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="titre" type="xs:string"/>
	<xs:element name="photo" type="xs:string"/>
	<xs:element name="synopsis" type="xs:string"/>
	<xs:element name="dateDiffusion" type="xs:date"/>
	<xs:element name="nbSaison" type="xs:int"/>
	<xs:element name="personnages">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="personnage" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="personnage">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="identite"/>
				<xs:element ref="descriptif"/>
			</xs:sequence>
			<xs:attribute name="idPerso" type="xs:ID" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="descriptif" type="xs:string"/>
	<xs:element name="role" type="xs:string"/>
	<xs:element name="employes">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="acteurs"/>
				<xs:element ref="producteurs"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="acteurs">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="acteur" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="acteur">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nom"/>
				<xs:element name="prenom"/>
				<xs:element name="dateNaissance"/>
			</xs:sequence>
			<xs:attribute name="idActeur" type="xs:ID" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="nom" type="xs:string"/>
	<xs:element name="prenom" type="xs:string"/>
	<xs:element name="dateNaissance" type="xs:date"/>
	<xs:element name="adresse">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="num"/>
				<xs:element ref="voie"/>
				<xs:element ref="ville"/>
				<xs:element ref="codePostal"/>
				<xs:element ref="pays"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="num" type="xs:int"/>
	<xs:element name="voie" type="xs:string"/>
	<xs:element name="ville" type="xs:string"/>
	<xs:element name="codePostal" type="xs:string"/>
	<xs:element name="pays" type="xs:string"/>
	<xs:element name="producteurs">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="producteur" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="producteur">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nom"/>
				<xs:element name="prenom"/>
			</xs:sequence>
			<xs:attribute name="idProducteur" type="xs:ID" use="required"/>
			<xs:attribute name="codeSerie" type="xs:IDREF" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="contrats">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="contrat" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="contrat">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="role"/>
				<xs:element ref="cachet"/>
				<xs:element ref="dateSignature"/>
			</xs:sequence>
			<xs:attribute name="numero" type="xs:ID" use="required"/>
			<xs:attribute name="idProducteur" type="xs:IDREF" use="required"/>
			<xs:attribute name="idActeur" type="xs:IDREF" use="required"/>
			<xs:attribute name="codeSerie" type="xs:IDREF" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="dateSignature" type="xs:date"/>
	<xs:element name="cachet" type="xs:int"/>
</xs:schema>

=== KhaledSARRAJ/XML/hbo (1).xml
<?xml version="1.0" encoding="UTF-8"?>
<HBO xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Users/formation/Desktop/XML/hbo.xsd">
	<series>
		<serie codeSerie="GOT">
			<titre>Game of Thrones</titre>
			<synopsis>Il y a tr√®s longtemps......</synopsis>
			<dateDiffusion>2011-04-17</dateDiffusion>
			<nbSaison>7</nbSaison>
			<personnages>
				<personnage idPerso="p1">
					<identite>Oberyn Martell</identite>
					<descriptif>Prince de Dorne</descriptif>
				</personnage>
				<personnage idPerso="p2">
					<identite>Jon Snow</identite>
					<descriptif>Lord Commandant de la garde de nuit</descriptif>
				</personnage>
			</personnages>
		</serie>
		<serie codeSerie="LS">
			<titre>Les Soprano</titre>
			<synopsis>Tony Soprano, un gangster.....</synopsis>
			<dateDiffusion>1999-10-01</dateDiffusion>
			<nbSaison>6</nbSaison>
			<personnages>
				<personnage idPerso="p3">
					<identite>Tony Soprano</identite>
					<descriptif>Chef de famille Soprano</descriptif>
				</personnage>
				<personnage idPerso="p4">
					<identite>Carmela Soprano</identite>
					<descriptif>Cheffe de la famille Soprano</descriptif>
				</personnage>
			</personnages>
		</serie>
	</series>
	<employes>
		<acteurs>
			<acteur idActeur="a1">
				<nom>Pascal</nom>
				<prenom>Pedro</prenom>
				<dateNaissance>1975-02-02</dateNaissance>
			</acteur>
			<acteur idActeur="a2">
				<nom>Harington</nom>
				<prenom>Kit</prenom>
				<dateNaissance>1986-02-02</dateNaissance>
			</acteur>
			<acteur idActeur="a3">
				<nom>Gandolfini</nom>
				<prenom>James</prenom>
				<dateNaissance>1961-02-01</dateNaissance>
			</acteur>
			<acteur idActeur="a4">
				<nom>Falco</nom>
				<prenom>Eddie</prenom>
				<dateNaissance>1963-12-01</dateNaissance>
			</acteur>
		</acteurs>
		<producteurs>
			<producteur codeSerie="GOT" idProducteur="pr1">
				<nom>Huffam</nom>
				<prenom>Mark</prenom>
			</producteur>
			<producteur codeSerie="LS" idProducteur="pr2">
				<nom>Grey</nom>
				<prenom>Mark</prenom>
			</producteur>
		</producteurs>
	</employes>
	<contrats>
		<contrat numero="n1" idActeur="a1" codeSerie="GOT" idProducteur="pr1">
			<role idPerso="p1"/>
			<cachet>500</cachet>
			<dateSignature>2012-02-02</dateSignature>
		</contrat>
		<contrat numero="n2" idActeur="a2" codeSerie="GOT" idProducteur="pr1">
			<role idPerso="p2"/>
			<cachet>600</cachet>
			<dateSignature>2012-02-02</dateSignature>
		</contrat>
		<contrat numero="n3" idActeur="a3" codeSerie="LS" idProducteur="pr2">
			<role idPerso="p3"/>
			<cachet>500</cachet>
			<dateSignature>2012-02-02</dateSignature>
		</contrat>
		<contrat numero="n4" idActeur="a4" codeSerie="LS" idProducteur="pr2">
			<role idPerso="p4"/>
			<cachet>700</cachet>
			<dateSignature>2012-02-02</dateSignature>
		</contrat>
	</contrats>
</HBO>
